### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by steveharoz** [tidyverse/tidyverse#148] opened 2018-08-06 09:41 UTC
I'd like to acknowledge that I used a variety of tidyverse packages, but I'm not even sure where one ends and another begins. It'd be very useful if one could cite the tidyverse as a whole and get a reasonable description and set of authors for all of the packages included by default.

```r
> citation("tidyverse")

To cite package ‘tidyverse’ in publications use:

  Hadley Wickham (2017). tidyverse: Easily Install and Load the 'Tidyverse'. R package version 1.2.1.
  https://CRAN.R-project.org/package=tidyverse

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {tidyverse: Easily Install and Load the 'Tidyverse'},
    author = {Hadley Wickham},
    year = {2017},
    note = {R package version 1.2.1},
    url = {https://CRAN.R-project.org/package=tidyverse},
  }
```

@hadley has certainly contributed a lot, but I'd rather not use his name exclusively for the contribution.

**Comment by jennybc** [comment] 2018-08-06 22:17
I believe @hadley is working towards a submission to [JOSS](https://joss.theoj.org) that would provide exactly what you are after, for all the reasons you give.

**Comment by hadley** [comment] 2019-05-10 14:45
Duplicate of #111

**Closed by hadley** 2019-05-10 14:45 UTC
