### ISSUE TITLE
cli::symbol$tick causes pandoc to fail during kniting

### ISSUE THREAD

**Issue by maptracker** [tidyverse/tidyverse#96] opened 2017-11-21 15:16 UTC
The unicode checkmarks generated (in [attach.R](https://github.com/tidyverse/tidyverse/commit/c704b28052357230a128d95b7c3381318e45cbb1#diff-bad55cdd46f463abc12ea0917fb6a1dfL6)) during initial attachment of tidyverse will cause `rmarkdown` to fail if pandoc is configured to use pdflatex (I think the default)? Given that the checkmarks are aesthetic only, is it possible to keep the attachment manifest as pure ASCII (a "+" was used prior to the change)?

Quick replication: Given a file `loadTidyVerse.R` with the content:

```R
library("tidyverse")
message("done")
```

... then the command:

```R
library("rmarkdown")
render("loadTidyVerse.R", pdf_document()  )
```

... fails with (presuming pdflatex is used by pandoc):

```
processing file: loadTidyVerse.spin.Rmd
  |......................                                           |  33%
  ordinary text without R code
  |...........................................                      |  67%
label: unnamed-chunk-1
  |.................................................................| 100%
  ordinary text without R code

output file: loadTidyVerse.knit.md

/usr/local/bin/pandoc +RTS -K512m -RTS loadTidyVerse.utf8.md --to latex
    --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    --output loadTidyVerse.pdf 
    --template /usr/lib64/R/library/rmarkdown/rmd/latex/default-1.17.0.2.tex
    --highlight-style tango --pdf-engine pdflatex --variable graphics=yes 
    --variable 'geometry:margin=1in' 
Error producing PDF.
! Package inputenc Error: Unicode char \u8:√ not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.145 \end{verbatim}
Try running pandoc with --pdf-engine=xelatex.
Error: pandoc document conversion failed with error 43
```

This is in the context of [RStudio](https://www.rstudio.com/) in [Domino](https://www.dominodatalab.com/), though it's presumably a problem in other contexts. We're looking into switching to xelatex, which to be honest we may need to do for other lurking Unicode characters.

For other readers with the same problem, note also that the issue displays the initially baffling behavior of causing knitr to fail the first time, but succeeds on subsequent tries in the same R session - this is because the manifest with the checkmark is generated only on the initial loading of the library. The second knit attempt will not encounter the ticks and will process the document appropriately.

```
R version 3.4.1 (2017-06-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS release 6.9 (Final)

Matrix products: default
BLAS: /usr/lib64/R/lib/libRblas.so
LAPACK: /usr/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] forcats_0.2.0   stringr_1.2.0   dplyr_0.7.4     purrr_0.2.4     readr_1.1.1     tidyr_0.7.2    
 [7] tibble_1.3.4    ggplot2_2.2.1   tidyverse_1.2.0 rmarkdown_1.8   knitr_1.17     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13     cellranger_1.1.0 compiler_3.4.1   plyr_1.8.4       bindr_0.1       
 [6] tools_3.4.1      digest_0.6.12    lubridate_1.7.1  jsonlite_1.5     evaluate_0.10.1 
[11] nlme_3.1-131     gtable_0.2.0     lattice_0.20-35  pkgconfig_2.0.1  rlang_0.1.4     
[16] psych_1.7.8      cli_1.0.0        rstudioapi_0.7   yaml_2.1.14      parallel_3.4.1  
[21] haven_1.1.0      bindrcpp_0.2     xml2_1.1.1       httr_1.3.1       hms_0.3         
[26] rprojroot_1.2    grid_3.4.1       glue_1.2.0       R6_2.2.2         readxl_1.0.0    
[31] foreign_0.8-69   modelr_0.1.1     reshape2_1.4.2   magrittr_1.5     backports_1.1.1 
[36] scales_0.5.0     htmltools_0.3.6  rvest_0.3.2      assertthat_0.2.0 mnormt_1.5-5    
[41] colorspace_1.3-2 stringi_1.1.5    lazyeval_0.2.1   munsell_0.4.3    broom_0.4.2     
[46] crayon_1.3.4 
```
pandoc 2.0.1.1, Compiled with pandoc-types 1.17.2, texmath 0.10, skylighting 0.4.3.2

**Comment by hadley** [comment] 2017-11-21 16:40
Duplicate of https://github.com/r-lib/cli/issues/34

**Closed by hadley** 2017-11-21 16:40 UTC
