### ISSUE TITLE
Intra-tidyverse masking

### ISSUE THREAD

**Issue by AHoerner** [tidyverse/tidyverse#54] opened 2017-03-26 23:01 UTC
Is there an order, or a method, of installing the secondary tidyverse packages (hms stringr, etc.) such that they do not mask each other's functions? 

For instance, with my current order, I get hms() masked from hms by lubridate, as_factor() masked from forecats by haven, guess_encoding() masked from readr, and bootstrap() masked from modelr by broom.

If these conflicts are illusory, e.g. the masking functions are identical to the masked functions, a reassuring comment in the tidyverse documentation would be appreciated. 

If the conflicts are real and can not be eliminated by an installation method, then I would put this forward as a feature request: name changes such that tidyverse packages can be installed in any combination and order without masking one another's functions.

**Comment by hadley** [comment] 2017-03-27 12:52
I think you mean attached/loaded, not installed?

**Comment by hadley** [comment] 2017-04-17 22:52
Duplicate of #26

**Closed by hadley** 2017-04-17 22:52 UTC
